# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Build
      run: docker build -t deepvariant . --build-arg DV_OPENVINO_BUILD=1

    - name: Download testdata
      run: |
        mkdir -p input
        FTPDIR=ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids
        curl ${FTPDIR}/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz | gunzip > input/GRCh38_no_alt_analysis_set.fasta
        curl ${FTPDIR}/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.fai > input/GRCh38_no_alt_analysis_set.fasta.fai
        HTTPDIR=https://storage.googleapis.com/deepvariant/case-study-testdata
        curl ${HTTPDIR}/HG002.novaseq.pcr-free.35x.dedup.grch38_no_alt.chr20.bam > input/HG002.novaseq.pcr-free.35x.dedup.grch38_no_alt.chr20.bam
        curl ${HTTPDIR}/HG002.novaseq.pcr-free.35x.dedup.grch38_no_alt.chr20.bam.bai > input/HG002.novaseq.pcr-free.35x.dedup.grch38_no_alt.chr20.bam.bai
    - name: Test WGS
      run: .github/workflows/run_test.sh WGS

    - name: Test WES
      run: .github/workflows/run_test.sh WES

    - name: Test PACBIO
      run: .github/workflows/run_test.sh PACBIO

    - name: Test HYBRID_PACBIO_ILLUMINA
      run: .github/workflows/run_test.sh HYBRID_PACBIO_ILLUMINA
